autofetch_sources: true
networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      # fork: https://mainnet.infura.io/v3/cf64e9aa7e5047a8afd17394a21ac158@12955063
      fork: https://eth-mainnet.alchemyapi.io/v2/oFgvsC3LQVCvgHjjM_om-MlV__yyrkdb
    explorer: 'https://api.etherscan.io/api'

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"

test_config:
  parameter_contract:
    decimal: 1000000000000000000
    transferAmt: 10000
    maxReceivePercentage_multiply_100: 80
    numTokensSellToAddToLiquidity: 20000
    buyAmt_ETH: 2